export const projects = [
  {
    title: "Yoga website",
    description: "The description of project",
    status: "",
    author: "Donnchadh",
    project: "Project 1",
    date: "19 Feb 2022",
    image: "/static/images/project_1.png",
    tags: ["HTML", "CSS", "jQuery"],
    website: "https://dmcginley.github.io/project1_yoga_site/",
    source: "https://github.com/dmcginley/project1_yoga_site",
    id: 1,
  },
  {
    title: "Chartjs",
    description: "The description of project",
    status: "",
    author: "Donnchadh",
    project: "Project 2",
    date: "7 May 2022",
    image: "/static/images/project_2.png",
    tags: ["HTML & CSS", "JavaScript", "jQuery"],
    website: "https://dmcginley.github.io/project2-chart-my-data/",
    source: "https://github.com/dmcginley/project2-chart-my-data",
    id: 2,
  },
  // {
  //   title: "Project 3 - Battleship Game",
  //   description: "The description of project",
  //   author: "Donnchadh",
  //   date: "29 Nov 2022",
  //   image: "/static/images/small/project_3_sm.png",
  //   tags: ["Python"],
  //   website: "https://www.google.com/",
  //   source: "https://github.com/",
  //   id: 3,
  // },
  {
    title: "Tech Blog",
    description: "The description of project",
    status: "",
    author: "Donnchadh",
    project: "Project 3",
    date: "18 Sep 2022",
    image: "/static/images/project_4.png",
    tags: ["Django", "Python", "jQuery"],
    website: "https://web-production-ce89.up.railway.app/",
    source: "https://github.com/dmcginley/blog_django_bootstrap5_project4",
    id: 3,
  },
  {
    title: "eCommerce",
    description: "The description of project",
    status: "",
    author: "Donnchadh",
    project: "Project 4",
    date: "19 Dec 2022",
    image: "/static/images/project_5.png",
    tags: ["Django", "Python", "jQuery", "Stripe"],
    website: "https://web-production-7efa.up.railway.app/",
    source: "https://github.com/dmcginley/django_shop_project",
    id: 4,
  },
  {
    title: "Portfolio",
    description: "The description of project",
    status: "",
    author: "Donnchadh",
    project: "Project 5",
    image: "/static/images/project_7.png",
    date: "18 Jan 2023",
    tags: ["Next.js", "TailwindCSS"],
    website: "/",
    source: "https://github.com/dmcginley/portfolio_nextjs_app",
    id: 5,
  },
  {
    title: "Old style Blog",
    description: "The description of project",
    status: "Currently working on",
    author: "Donnchadh",
    project: "Project 6",
    date: "11 Mar 2023",
    image: "/static/images/project_6.png",
    tags: ["Django", "Python", "jQuery"],
    website: "https://web-production-9d71.up.railway.app/",
    source: "https://github.com/dmcginley/message_board_project",
    id: 6,
  },
];
