export const projects = [
  {
    title: "Project 1 - Yoga website",
    description: "The description of project",
    author: "Donnchadh",
    date: "19 Feb 2022",
    image: "/static/images/project_1.png",
    tags: ["HTML", "CSS", "jQuery"],
    website: "https://dmcginley.github.io/project1_yoga_site/",
    source: "https://github.com/dmcginley/project1_yoga_site",
    id: 1,
  },
  {
    title: "Project 2 - Chartjs",
    description: "The description of project",
    author: "Donnchadh",
    date: "7 May 2022",
    image: "/static/images/project_2.png",
    tags: ["HTML & CSS", "JavaScript", "jQuery"],
    website: "https://dmcginley.github.io/project2-chart-my-data/",
    source: "https://github.com/dmcginley/project2-chart-my-data",
    id: 2,
  },
  // {
  //   title: "Project 3 - Battleship Game",
  //   description: "The description of project",
  //   author: "Donnchadh",
  //   date: "29 Nov 2022",
  //   image: "/static/images/small/project_3_sm.png",
  //   tags: ["Python"],
  //   website: "https://www.google.com/",
  //   source: "https://github.com/",
  //   id: 3,
  // },
  {
    title: "Project 3 - Tech Blog",
    description: "The description of project",
    author: "Donnchadh",
    date: "18 Sep 2022",
    image: "/static/images/project_4.png",
    tags: ["Django", "Python", "jQuery"],
    website: "https://www.google.com/",
    source: "https://github.com/dmcginley/blog_django_bootstrap5_project4",
    id: 3,
  },
  {
    title: "Project 4 - eCommerce",
    description: "The description of project",
    author: "Donnchadh",
    date: "19 Dec 2022",
    image: "/static/images/project_5.png",
    tags: ["Django", "Python", "jQuery", "Stripe"],
    website: "https://web-production-7efa.up.railway.app/",
    source: "https://github.com/dmcginley/django_shop_project",
    id: 4,
  },
  {
    title: "Project 5 - Portfolio",
    description: "The description of project",
    author: "Donnchadh",
    image: "/static/images/project_7.png",
    date: "18 Jan 2023",
    tags: ["Next.js", "TailwindCSS"],
    website: "",
    source: "https://github.com/dmcginley/message_board_project",
    id: 5,
  },
  {
    title: "Project 6 - Old style Blog",
    description: "The description of project",
    author: "Donnchadh",
    date: "10 Feb 2023",
    image: "/static/images/project_6.png",
    tags: ["Django", "Python", "jQuery"],
    website: "https://web-production-9d71.up.railway.app/",
    source: "https://github.com/dmcginley/message_board_project",
    id: 6,
  },
];
