export const projects = [
  {
    title: "Project 1 - Yoga website",
    description: "The description of project",
    author: "Donnchadh",
    date: "29 Nov 2022",
    image: "/static/images/small/project_1_sm.png",
    tags: ["HTML", "CSS", "jQuery"],
    website: "https://www.google.com/",
    source: "https://github.com/",
    id: 1,
  },
  {
    title: "Project 2 - Chartjs",
    description: "The description of project",
    author: "Donnchadh",
    date: "29 Nov 2022",
    image: "/static/images/small/project_2_sm.png",
    tags: ["HTML & CSS", "JavaScript", "jQuery"],
    website: "https://www.google.com/",
    source: "https://github.com/",
    id: 2,
  },
  {
    title: "Project 3 - Battleship Game",
    description: "The description of project",
    author: "Donnchadh",
    date: "29 Nov 2022",
    image: "/static/images/small/project_3_sm.png",
    tags: ["Python"],
    website: "https://www.google.com/",
    source: "https://github.com/",
    id: 3,
  },
  {
    title: "Project 4 - Tech Blog",
    description: "The description of project",
    author: "Donnchadh",
    date: "29 Nov 2022",
    image: "/static/images/small/project_4_sm.png",
    tags: ["Django", "Python", "jQuery"],
    website: "https://www.google.com/",
    source: "https://github.com/",
    id: 4,
  },
  {
    title: "Project 5 - eCommerce Store",
    description: "The description of project",
    author: "Donnchadh",
    date: "29 Nov 2022",
    image: "/static/images/small/project_5_sm.png",
    tags: ["Django", "Python", "jQuery", "Stripe"],
    website: "https://www.google.com/",
    source: "https://github.com/",
    id: 5,
  },
];
