import Head from "next/head";
import Image from "next/image";
// import { Inter } from "@next/font/google";
// import Hero from "../components/Hero/Hero";
import Hero from "../components/Hero";

import { Layout } from "../layout/Layout";

import styles from "../styles/Home.module.css";
import {
  SiDjango,
  SiPython,
  SiJavascript,
  SiGithub,
  SiTwitter,
} from "react-icons/si";
import { RiLinkedinFill } from "react-icons/ri";
import Projects from "../components/Projects";

// const inter = Inter({ subsets: ["latin"] });
const social_icons = { color: "rgb(40, 98, 170)", fontSize: "2.6rem" };

export default function Home() {
  return (
    <Layout className="">
      <section className="main-grid">
        <Hero />
        <Projects />
        <h1>test section in index file</h1>
      </section>
    </Layout>

    // <div>
    //   <Head>
    //     <title>Portfolio</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <meta
    //       name="keywords"
    //       content="fullstack developer,frontend, portfoliort"
    //     />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <main className="bg-slate-50 main-grid">
    //     {/* navbar */}
    //     <nav className=" bg-gray-200">
    //       {/* <div className="px-2 sm:px-6 lg:px-8"> */}
    //       <div className="px-6 md:px-10 flex h-16 items-center justify-center md:justify-start">
    //         <div className=" inset-y-0 flex items-center">
    //           <ul className="flex align-middle justify-center">
    //             <li className="mr-3">
    //               <a
    //                 className="inline-block rounded py-1.5 px-4 bg-darkBlue text-white"
    //                 href="#"
    //               >
    //                 Home
    //               </a>
    //             </li>
    //             <li className="mr-3">
    //               <a
    //                 className="inline-block rounded hover:border-gray-200 text-darkBlue hover:bg-gray-200 py-1.5 px-4"
    //                 href="#"
    //               >
    //                 Resume
    //               </a>
    //             </li>
    //             <li className="mr-3">
    //               <a
    //                 className="inline-block rounded hover:border-gray-200 text-darkBlue hover:bg-gray-200 py-1.5 px-4 "
    //                 href="#"
    //               >
    //                 Contact
    //               </a>
    //             </li>
    //           </ul>
    //         </div>
    //       </div>
    //       {/*
    //             </div> */}
    //     </nav>
    //     {/* hero */}
    //     <section className="p-8 md:px-12 md:py-16 pb-4 md:pb-24 bg-gray-200">
    //       <div className="hero flex justify-center lg:justify-start lg:px-24 items-end px-3">
    //         <img
    //           className="rounded-3xl h-36 w-36 md:h-44  md:w-44"
    //           src="static/images/cat_3.png"
    //           alt=""
    //         />

    //         <div className="pl-6">
    //           <h1 className="text-4xl pb-2 pl-2">Donnchadh Mc Ginley</h1>
    //           <p className="text-darkBlue text-lg pl-2">Fullstack develiper</p>
    //           {/* social icons desktop*/}
    //           <div className="pt-4 hidden md:flex">
    //             <a
    //               className="p-2"
    //               href="https://github.com/dmcginley"
    //               target="_blank"
    //               rel="noopener noreferrer"
    //             >
    //               <SiGithub
    //                 style={social_icons}
    //                 className="hover:fill-darkBlueHover transition-all"
    //               />
    //             </a>
    //             <a
    //               className="p-2 mx-12"
    //               href="https://www.linkedin.com/in/donnchadh-mc-ginley/"
    //               target="_blank"
    //               rel="noopener noreferrer"
    //             >
    //               <RiLinkedinFill
    //                 style={social_icons}
    //                 className="hover:fill-darkBlueHover transition-all"
    //               />
    //             </a>
    //             <a
    //               className="p-2"
    //               href=""
    //               target="_blank"
    //               rel="noopener noreferrer"
    //             >
    //               <SiTwitter
    //                 style={social_icons}
    //                 className="hover:fill-darkBlueHover transition-all"
    //               />
    //             </a>
    //           </div>
    //         </div>
    //       </div>
    //     </section>
    //     {/* social icons mobile */}
    //     <div className="flex justify-center pt-4 md:hidden bg-gray-200 pb-10">
    //       <a
    //         className="p-2"
    //         href="https://github.com/dmcginley"
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <SiGithub style={social_icons} />
    //       </a>
    //       <a
    //         className="p-2 mx-12"
    //         href="https://www.linkedin.com/in/donnchadh-mc-ginley/"
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <RiLinkedinFill style={social_icons} />
    //       </a>
    //       <a className="p-2" href="" target="_blank" rel="noopener noreferrer">
    //         <SiTwitter style={social_icons} />
    //       </a>
    //     </div>

    //     <div className="px-8 pb-2">
    //       <section className="text-3xl px-6 py-8 md:pt-16 font-semibold text-darkBlue md:items-center text-center md:text-left">
    //         <h3>My Projects</h3>
    //       </section>
    //       {/* cards */}
    //       <section className="flex flex-col md:grid md:grid-cols-2 xl:grid-cols-3 gap-10 xl:gap-14 md:px-6">
    //         <div className="card">
    //           <a href="#" className="group bg-slate-700">
    //             <div className=" relative mx-auto max-w-md md:max-w-none flex flex-col lg:flex-row">
    //               <img
    //                 src="/static/images/project_1.png"
    //                 className="flex-1 rounded-md"
    //                 alt=""
    //               />
    //               <div className="absolute flex flex-col justify-end h-full w-full ">
    //                 <div className="bg-gradient-to-t from-slate-800 group-hover:bg-slate-900 p-6 transition-all rounded-b-md">
    //                   <h3 className="text-2xl pb-1 text-gray-50">
    //                     Yoga website - P1
    //                   </h3>
    //                   <p className="text-sm text-gray-300">
    //                     Donnchadh • <time>29 Nov 2022</time>
    //                   </p>
    //                   {/* <p className="text-gray-50">
    //                     Lorem ipsum dolor sit amet consectetur adipisicing elit.
    //                     Excepturi obcaecati facere quod!
    //                   </p> */}

    //                   <div className="mt-4 flex gap-2">
    //                     <span className="inline-flex items-center gap-1 rounded-full border-solid border-blue-300 border px-2 py-1 text-xs font-semibold text-blue-300">
    //                       HTML5
    //                     </span>
    //                     <span className="inline-flex items-center gap-1 rounded-full border-solid border-indigo-300 border px-2 py-1 text-xs font-semibold text-indigo-300">
    //                       CSS3
    //                     </span>
    //                     <span className="inline-flex items-center gap-1 rounded-full border-solid border-orange-300 border px-2 py-1 text-xs font-semibold text-orange-300">
    //                       jQueiry
    //                     </span>
    //                   </div>
    //                 </div>
    //               </div>
    //             </div>
    //           </a>
    //         </div>
    //         <div className="card">
    //           <a href="#" className="group bg-slate-700">
    //             <div className=" relative rounded mx-auto max-w-md md:max-w-none flex flex-col lg:flex-row">
    //               <img
    //                 src="/static/images/project_2.png"
    //                 className="flex-1 rounded-md"
    //                 alt=""
    //               />
    //               <div className="absolute flex flex-col justify-end h-full w-full">
    //                 <div className="bg-gradient-to-t from-slate-800 group-hover:bg-slate-900 p-6 transition-all rounded-b-md">
    //                   <h3 className="text-2xl pb-1 text-gray-50">
    //                     Chartjs website - P2
    //                   </h3>
    //                   <p className="text-sm text-gray-300">
    //                     Donnchadh • <time>29 Nov 2022</time>
    //                   </p>
    //                   {/* <p className="text-gray-50">
    //                     Lorem ipsum dolor sit amet consectetur adipisicing elit.
    //                     Excepturi obcaecati facere quod!
    //                   </p> */}

    //                   <div className="mt-4 flex gap-2">
    //                     <span className="inline-flex items-center gap-1 rounded-full border-solid border-blue-300 border px-2 py-1 text-xs font-semibold text-blue-300">
    //                       HTML, CSS
    //                     </span>
    //                     <span className="inline-flex items-center gap-1 rounded-full border-solid border-yellow-300 border px-2 py-1 text-xs font-semibold text-yellow-300">
    //                       JavaScript
    //                     </span>
    //                     <span className="inline-flex items-center gap-1 rounded-full border-solid border-red-300 border px-2 py-1 text-xs font-semibold text-red-300">
    //                       Chart.js
    //                     </span>
    //                   </div>
    //                 </div>
    //               </div>
    //             </div>
    //           </a>
    //         </div>
    //         <div className="card">
    //           <a href="#" className="group bg-slate-700">
    //             <div className=" relative rounded mx-auto max-w-md md:max-w-none flex flex-col lg:flex-row">
    //               <img
    //                 src="/static/images/project_2.png"
    //                 className="flex-1 rounded-md"
    //                 alt=""
    //               />
    //               <div className="absolute flex flex-col justify-end h-full w-full">
    //                 <div className="bg-gradient-to-t from-slate-800 group-hover:bg-slate-900 p-6 transition-all rounded-b-md">
    //                   <h3 className="text-2xl pb-1 text-gray-50">
    //                     Battleship Game - P3
    //                   </h3>
    //                   <p className="text-sm text-gray-300">
    //                     Donnchadh • <time>29 Nov 2022</time>
    //                   </p>
    //                   {/* <p className="text-gray-50">
    //                     Lorem ipsum dolor sit amet consectetur adipisicing elit.
    //                     Excepturi obcaecati facere quod!
    //                   </p> */}

    //                   <div className="mt-4 flex gap-2">
    //                     <span className="inline-flex items-center gap-1 rounded-full border-solid border-green-300 border px-2 py-1 text-xs font-semibold text-green-300">
    //                       Python
    //                     </span>
    //                   </div>
    //                 </div>
    //               </div>
    //             </div>
    //           </a>
    //         </div>
    //         <div className="card">
    //           <a href="#" className="group bg-slate-700">
    //             <div className=" relative rounded mx-auto max-w-md md:max-w-none flex flex-col lg:flex-row">
    //               <img
    //                 src="/static/images/project_2.png"
    //                 className="flex-1 rounded-md"
    //                 alt=""
    //               />
    //               <div className="absolute flex flex-col justify-end h-full w-full">
    //                 <div className="bg-gradient-to-t from-slate-800 group-hover:bg-slate-900 p-6 transition-all rounded-b-md">
    //                   <h3 className="text-2xl pb-1 text-gray-50">Blog - P4</h3>
    //                   <p className="text-sm text-gray-300">
    //                     Donnchadh • <time>29 Nov 2022</time>
    //                   </p>
    //                   {/* <p className="text-gray-50">
    //                     Lorem ipsum dolor sit amet consectetur adipisicing elit.
    //                     Excepturi obcaecati facere quod!
    //                   </p> */}

    //                   <div className="mt-4 flex gap-2">
    //                     <span className="inline-flex items-center gap-1 rounded-full border-solid border-purple-300 border px-2 py-1 text-xs font-semibold text-purple-300">
    //                       Django
    //                     </span>
    //                     <span className="inline-flex items-center gap-1 rounded-full border-solid border-green-300 border px-2 py-1 text-xs font-semibold text-green-300">
    //                       Python
    //                     </span>
    //                   </div>
    //                 </div>
    //               </div>
    //             </div>
    //           </a>
    //         </div>
    //         <div className="card">
    //           <a href="#" className="group bg-slate-700">
    //             <div className=" relative rounded mx-auto max-w-md md:max-w-none flex flex-col lg:flex-row">
    //               <img
    //                 src="/static/images/project_5.png"
    //                 className="flex-1 rounded-md"
    //                 alt=""
    //               />
    //               <div className="absolute flex flex-col justify-end h-full w-full">
    //                 <div className="bg-gradient-to-t from-slate-800 group-hover:bg-slate-900 p-6 transition-all rounded-b-md">
    //                   <h3 className="text-2xl pb-1 text-gray-50">
    //                     eCommerce store - P5
    //                   </h3>
    //                   <p className="text-sm text-gray-300">
    //                     Donnchadh • <time>29 Nov 2022</time>
    //                   </p>
    //                   {/* <p className="text-gray-50">
    //                     Lorem ipsum dolor sit amet consectetur adipisicing elit.
    //                     Excepturi obcaecati facere quod!
    //                   </p> */}

    //                   <div className="mt-4 flex gap-2">
    //                     <span className="inline-flex items-center gap-1 border-purple-300 border px-2 py-1 text-xs font-semibold text-purple-300">
    //                       Django
    //                     </span>
    //                     <span className="inline-flex items-center gap-1 rounded-full border-solid border-green-300 border px-2 py-1 text-xs font-semibold text-green-300">
    //                       Python
    //                     </span>
    //                     <span className="inline-flex items-center gap-1 rounded-full border-solid border-yellow-300 border px-2 py-1 text-xs font-semibold text-yellow-300">
    //                       JavaScript
    //                     </span>
    //                   </div>
    //                 </div>
    //               </div>
    //             </div>
    //           </a>
    //         </div>
    //       </section>
    //     </div>

    //     <section className="card-section  m-auto md:flex md:justify-center px-10 pt-24 gap-6">
    //       <div className="block rounded-lg shadow-lg bg-white md:max-w-sm text-center mb-6 flex-1">
    //         <div className="bg-slate-400 p-3 rounded-t">
    //           <SiDjango size={50} />
    //         </div>
    //         <h3 className=" text-xl py-3 px-6 border-gray-300">
    //           Lorem ipsum dolor
    //         </h3>
    //         <div className="p-6">
    //           <p className="text-gray-700 text-base mb-4">
    //             With supporting text below as a natural lead-in to additional
    //             content.
    //           </p>
    //           <button
    //             type="button"
    //             className=" inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
    //           >
    //             Button
    //           </button>
    //         </div>
    //         <div className="py-3 px-6 border-t border-gray-300 text-gray-600">
    //           2 days ago
    //         </div>
    //       </div>
    //       <div className="block rounded-lg shadow-lg bg-white md:max-w-sm text-center mb-6 flex-1">
    //         <div className="bg-orange-400 p-3 rounded-t">
    //           <SiPython size={50} />
    //         </div>
    //         <h3 className=" text-xl py-3 px-6 border-gray-300">
    //           Lorem ipsum dolor
    //         </h3>
    //         <div className="p-6">
    //           <p className="text-gray-700 text-base mb-4">
    //             With supporting text below as a natural lead-in to additional
    //             content.
    //           </p>
    //           <button
    //             type="button"
    //             className=" inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
    //           >
    //             Button
    //           </button>
    //         </div>
    //         <div className="py-3 px-6 border-t border-gray-300 text-gray-600">
    //           2 days ago
    //         </div>
    //       </div>
    //       <div className="block rounded-lg shadow-lg bg-white md:max-w-sm text-center mb-6 flex-1">
    //         <div className="bg-violet-400 p-3 rounded-t">
    //           <SiJavascript size={50} />
    //         </div>
    //         <h3 className=" text-lg py-3 px-4 pb-0 border-gray-300">
    //           Lorem ipsum dolor
    //         </h3>
    //         <div className="p-4">
    //           <p className="text-gray-700 text-base mb-4">
    //             With supporting text bedf additional content.
    //           </p>
    //           <button
    //             type="button"
    //             className=" inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
    //           >
    //             Button
    //           </button>
    //         </div>
    //         <div className="py-3 px-6 border-t border-gray-300 text-gray-600">
    //           2 days ago
    //         </div>
    //       </div>
    //     </section>
    //     <section>
    //       <div></div>
    //     </section>
    //   </main>
    // </div>
  );
}
